# Generated by Django 5.2 on 2025-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("morning_mood", models.CharField(max_length=10)),
                ("afternoon_mood", models.CharField(max_length=10)),
                ("evening_mood", models.CharField(max_length=10)),
                ("water_intake", models.IntegerField()),
                ("energy_level", models.IntegerField()),
                ("stress_level", models.IntegerField()),
                ("feelings", models.TextField()),
                ("activities", models.TextField()),
                ("needs", models.TextField()),
                ("todo_list", models.TextField()),
                ("reflections", models.TextField()),
                ("notes", models.TextField()),
            ],
        ),
    ]
